name: dotnet package

on:
  push:
    branches: [ master, setup-artifacts ]
  pull_request:
    branches: [ master, setup-artifacts]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x', '5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - uses: actions/upload-artifact@main
        with:
            name: webpack artifacts
            path: public/

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x', '5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@main
        with:
            name: webpack artifacts
            path: public
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
      - name: Install dependencies
        run: dotnet restore
      - name: Test with the dotnet CLI
        run: dotnet test ./PrimeService.Tests/PrimeService.Tests.csproj
